language: node_js

node_js:
 - "0.12.7"

branches:
  only:
  - master


before_install:
 - openssl aes-256-cbc -K $encrypted_f739449d5e95_key -iv $encrypted_f739449d5e95_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
 # set pemission 
 - chmod 600 ~/.ssh/id_rsa
 # Start SSH agent
 - eval $(ssh-agent)
 # Add the private key to the system
 - ssh-add ~/.ssh/id_rsa
 # Copy SSH config
 - cp .travis/ssh_config ~/.ssh/config
 # Set Git config
 - git config --global user.name "jsntxzx-from-travis"
 - git config --global user.email "jsntxzx@sina.com"

install:
 - npm install hexo-cli -g
 - npm install hexo --save
 - npm install

script:
 - hexo clean 
 - hexo generate 
 - hexo deploy
