language: node_js

sudo: false

# master为hexo博客所在分支
branches:
  only:
  - master

before_install:
- mkdir -pv ~/.ssh/
- openssl aes-256-cbc -K $encrypted_f739449d5e95_key -iv $encrypted_f739449d5e95_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'jsntxzx-travis'
- git config --global user.email 'jsntxzx@sina.com'

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g
- hexo d


